# numpy学习

## 1.创建数组与基本属性

In [35]:
import numpy as np

a=np.array([0.01,0.02,0.03])
print(a)
print(a.shape)
print(a.size)
print(a.dtype)

b=np.array([
    [0.1,0.2,-0.1],
    [-0.3,0.2,-0.2],
    [0.1,0.1,0],
    ])
print(b)
print(b.shape)
print(b.size)
print(b.ndim)

print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.eye(4))
print(np.arange(0,10,2))
print(np.linspace(0,1,4))

print(np.random.rand(2,3))
print(np.random.randn(3,3))
print(np.random.normal(0,0.02,size=(3,3)))

[0.01 0.02 0.03]
(3,)
3
float64
[[ 0.1  0.2 -0.1]
 [-0.3  0.2 -0.2]
 [ 0.1  0.1  0. ]]
(3, 3)
9
2
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0 2 4 6 8]
[0.         0.33333333 0.66666667 1.        ]
[[0.63051559 0.14655463 0.53617625]
 [0.88793175 0.13484743 0.10906576]]
[[-0.17513431  1.76052095 -0.70421935]
 [-1.33326087 -1.79975645 -0.29078824]
 [ 0.60989612 -1.34057236 -1.23217239]]
[[-0.00373784 -0.01990406  0.013547  ]
 [-0.02409788 -0.00683744 -0.03949394]
 [-0.0231369   0.01397954  0.00918644]]


In [36]:
# 模拟 252 个交易日、300 只股票的收益率矩阵
T, N = 252, 300
ret = np.random.normal(0, 0.02, size=(T, N))
print(ret.shape)   # (252, 300)

(252, 300)


## 2.索引、切片、布尔索引

In [37]:
import numpy as np

ret = np.array([
    [0.01, 0.02, -0.01, 0.00],
    [0.02, -0.01, 0.03, 0.01],
    [-0.01, 0.00, 0.01, 0.02],
])

# 1. 单个元素
print(ret[0, 1])       # 第 0 天，第 1 只股票

# 2. 取一行（某一天所有股票）
print(ret[0, :])

# 3. 取一列（某只股票所有天）
print(ret[:, 1])

# 4. 切片：前 2 天、前 3 只股票
print(ret[:2, :3])

# 5. 布尔索引：找出所有大于 0 的收益率
mask = ret > 0
print(mask)
print(ret[mask])

# 6. 按条件替换：把负收益设为 0
ret_clipped = ret.copy()
ret_clipped[ret_clipped < 0] = 0
print(ret_clipped)

0.02
[ 0.01  0.02 -0.01  0.  ]
[ 0.02 -0.01  0.  ]
[[ 0.01  0.02 -0.01]
 [ 0.02 -0.01  0.03]]
[[ True  True False False]
 [ True False  True  True]
 [False False  True  True]]
[0.01 0.02 0.02 0.03 0.01 0.01 0.02]
[[0.01 0.02 0.   0.  ]
 [0.02 0.   0.03 0.01]
 [0.   0.   0.01 0.02]]


In [38]:
import numpy as np

ret = np.array([
    [0.01, 0.02, -0.01, 0.00],
    [0.02, -0.01, 0.03, 0.01],
    [-0.01, 0.00, 0.01, 0.02],
])

# 找出某只股票收益率为正的交易日
stock_ret = ret[:, 1]
positive_days = stock_ret[stock_ret > 0]
print(positive_days)

# 找出极端收益
extreme = ret[np.abs(ret) > 0.015]
print(extreme)

[0.02]
[0.02 0.02 0.03 0.02]


## 3.轴 axis 与聚合

In [39]:
import numpy as np

ret= np.array([
    [0.01, 0.02, -0.01, 0.00],
    [0.02, -0.01, 0.03, 0.01],
    [-0.01, 0.00, 0.01, 0.02],
])

print(ret.mean())          # 所有元素的均值
print(ret.mean(axis=0))    # 按列求均值（每只股票的平均收益率）
print(ret.mean(axis=1))    # 按行求均值（每一天的平均收益率）   

print(ret.std())           # 所有元素的标准差
print(ret.std(axis=0))     # 按列求标准差（每只股票的收益率波动）   
print(ret.std(axis=1))     # 按行求标准差（每一天的收益率波动）

print(ret.sum())           # 所有元素的和
print(ret.sum(axis=0))     # 按列求和（每只股票的总收益率）
print(ret.sum(axis=1))     # 按行求和（每一天的总收益率）   

print(ret.max(axis=0))
print(ret.min(axis=1)) 

0.007500000000000001
[0.00666667 0.00333333 0.01       0.01      ]
[0.005  0.0125 0.005 ]
0.012990381056766582
[0.01247219 0.01247219 0.01632993 0.00816497]
[0.01118034 0.0147902  0.01118034]
0.09000000000000001
[0.02 0.01 0.03 0.03]
[0.02 0.05 0.02]
[0.02 0.02 0.03 0.02]
[-0.01 -0.01 -0.01]


In [40]:
import numpy as np

ret = np.array([
    [0.01, 0.02, -0.01, 0.00],
    [0.02, -0.01, 0.03, 0.01],
    [-0.01, 0.00, 0.01, 0.02],
])

daily_volatility = ret.std(axis=0)
annualized_volatility = daily_volatility * np.sqrt(252)
print(annualized_volatility)

[0.1979899  0.1979899  0.25922963 0.12961481]


## 4.广播broadcasting

广播：不同形状数组之间，自动做 “虚拟复制扩展”，让它们形状匹配，从而直接运算（+ - * /），不真的复制数据，节省内存。
以下是几个简单例子：

In [41]:
import numpy as np
a = np.array([1,2,3])  # shape (3,)
b = 2                  # 标量，相当于 shape ()
print(a + b)

[3 4 5]


In [42]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]]) # shape (2,3)
b = np.array([10,20,30])# shape (3,)
print(a + b)

[[11 22 33]
 [14 25 36]]


In [43]:
import numpy as np

a = np.array([[1],[2]])   # shape (2,1)
b = np.array([[10,20,30]])# shape (1,3)
print(a + b)

[[11 21 31]
 [12 22 32]]


下面是广播在量化中的应用：

In [44]:
import numpy as np

ret = np.array([
    [0.01, 0.02, -0.01, 0.00],
    [0.02, -0.01, 0.03, 0.01],
    [-0.01, 0.00, 0.01, 0.02],
])

mu=ret.mean(axis=0)
demeaned_ret = ret - mu
print(demeaned_ret)

sigma = ret.std(axis=0)
standardized_ret = demeaned_ret / sigma
print(standardized_ret)
print(standardized_ret.mean(axis=0))
print(standardized_ret.std(axis=0))

w = np.array([0.1, 0.2, 0.3, 0.4])
portfolio_return = ret @ w
print(portfolio_return)

[[ 0.00333333  0.01666667 -0.02       -0.01      ]
 [ 0.01333333 -0.01333333  0.02        0.        ]
 [-0.01666667 -0.00333333  0.          0.01      ]]
[[ 0.26726124  1.33630621 -1.22474487 -1.22474487]
 [ 1.06904497 -1.06904497  1.22474487  0.        ]
 [-1.33630621 -0.26726124  0.          1.22474487]]
[ 1.48029737e-16 -3.70074342e-17 -7.40148683e-17  0.00000000e+00]
[1. 1. 1. 1.]
[0.002 0.013 0.01 ]


## 5.向量化计算

In [45]:
import time

N = 1_000_000
x = np.random.normal(size=N)

y = np.random.normal(size=N)

# for 循环版
t0 = time.time()
s = 0.0
for i in range(N):
    s += x[i] * y[i]
t1 = time.time()
print("for 循环:", t1 - t0, "结果:", s)

# 向量化版
t0 = time.time()
s2 = np.dot(x, y)
t1 = time.time()
print("向量化:", t1 - t0, "结果:", s2)

for 循环: 0.41051554679870605 结果: -490.2432774309542
向量化: 0.0009186267852783203 结果: -490.2432774309424


In [ ]:
# 简单收益率 r=P(i+1)/P(i)-1
prices = np.array([100, 101, 102, 101, 103], dtype=float)
rets = prices[1:] / prices[:-1] - 1
print(rets)

# 对数收益率 r=ln(P(i+1)/P(i))
log_rets = np.diff(np.log(prices))
print(log_rets)

# 滚动均值（用pandas里面的rolling方法更方便，详见pandas学习的8.4节）
window = 3
roll_mean=np.array([
    prices[i:i+window].mean() 
    for i in range(len(prices)-window+1)
    ])
print(roll_mean)

[ 0.01        0.00990099 -0.00980392  0.01980198]
[ 0.00995033  0.0098523  -0.0098523   0.01960847]
[101.         101.33333333 102.        ]


## 6.矩阵运算

In [47]:
from numpy.linalg import inv,det, eig,svd,solve

A=np.array([[1,2],
            [2,1]])

print("行列式:",det(A))
print("逆矩阵:\n",inv(A))  
print(solve(A,np.array([1,2])))
print("特征值和特征向量:\n",eig(A))
eigvals, eigvecs = eig(A)
print(eigvals)
print(eigvecs)

行列式: -2.9999999999999996
逆矩阵:
 [[-0.33333333  0.66666667]
 [ 0.66666667 -0.33333333]]
[1. 0.]
特征值和特征向量:
 EigResult(eigenvalues=array([ 3.+0.j, -1.+0.j]), eigenvectors=array([[ 0.70710678+0.j, -0.70710678+0.j],
       [ 0.70710678+0.j,  0.70710678+0.j]]))
[ 3.+0.j -1.+0.j]
[[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]


In [48]:
# 收益率矩阵：3 天，4 只股票
ret = np.array([
    [0.01, 0.02, -0.01, 0.00],
    [0.02, -0.01, 0.03, 0.01],
    [-0.01, 0.00, 0.01, 0.02],
])

# 权重向量：4 只股票
w = np.array([0.4, 0.3, 0.2, 0.1])

# 组合每日收益
port_ret = ret @ w
print(port_ret)

# 转置
print(ret.T.shape)   # (4, 3)

# 矩阵乘法：协方差矩阵
# 协方差 Covariance
#协方差衡量两个变量，是不是倾向于 “一起变大、一起变小”，描述两个变量协同波动的方向和幅度。
# ret shape (3, 4)，ret.T shape (4, 3)
# ret.T @ ret shape (4, 4)，即 4 只股票的协方差（未除以 T）
mu=ret.mean(axis=0)
demeaned_ret = ret - mu
cov = demeaned_ret.T @ demeaned_ret / (ret.shape[0]-1)
print(cov)
print(cov.shape)

# 用 np.cov 更标准
cov2 = np.cov(ret, rowvar=False)
print(cov2)

[0.008 0.012 0.   ]
(4, 3)
[[ 2.33333333e-04 -3.33333333e-05  1.00000000e-04 -1.00000000e-04]
 [-3.33333333e-05  2.33333333e-04 -3.00000000e-04 -1.00000000e-04]
 [ 1.00000000e-04 -3.00000000e-04  4.00000000e-04  1.00000000e-04]
 [-1.00000000e-04 -1.00000000e-04  1.00000000e-04  1.00000000e-04]]
(4, 4)
[[ 2.33333333e-04 -3.33333333e-05  1.00000000e-04 -1.00000000e-04]
 [-3.33333333e-05  2.33333333e-04 -3.00000000e-04 -1.00000000e-04]
 [ 1.00000000e-04 -3.00000000e-04  4.00000000e-04  1.00000000e-04]
 [-1.00000000e-04 -1.00000000e-04  1.00000000e-04  1.00000000e-04]]


In [49]:
# 假设 4 只股票
cov = np.cov(ret, rowvar=False)
ones = np.ones(cov.shape[0])
print(ones)

# 最小方差权重：w = Σ^{-1} 1 / (1^T Σ^{-1} 1)
inv_cov = inv(cov)
w_mv = inv_cov @ ones / (ones @ inv_cov @ ones)
print(w_mv)
print(w_mv.sum())   # 应为 1

[1. 1. 1. 1.]
[ 0.325  0.175 -0.1    0.6  ]
1.0


## 7.随机数生成

In [50]:
import numpy as np
rng=np.random.default_rng(42)

# 正态分布
x = rng.normal(loc=0, scale=1, size=10)
print(x)

# 均匀分布
u = rng.uniform(0, 1, size=10)
print(u)

# 整数
i = rng.integers(0, 10, size=10)
print(i)

# 多维
ret = rng.normal(0, 0.02, size=(252, 5))
print(ret.shape)

[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519 -1.30217951
  0.1278404  -0.31624259 -0.01680116 -0.85304393]
[0.37079802 0.92676499 0.64386512 0.82276161 0.4434142  0.22723872
 0.55458479 0.06381726 0.82763117 0.6316644 ]
[1 7 7 3 0 9 4 8 6 7]
(252, 5)


In [51]:
rng=np.random.default_rng(42)

T=252
mu=0.08
sigma=0.2
S0=100
dt=1/T

eps=rng.normal(0,1,size=T)
log_ret=(mu-0.5*sigma**2)*dt + sigma*np.sqrt(dt)*eps
print(log_ret.shape)

log_price=np.log(S0)+np.cumsum(log_ret) #cumsum返回累积求和数组
price=np.exp(log_price)

print(price[:5])
print(price[-1])

(252,)
[100.40854926  99.12511922 100.09059984 101.30784698  98.87152039]
91.06737490367291


## 8.for循环与向量化的欧式距离（距离矩阵）

In [52]:
import numpy as np
import time

def euclidean_loop(X,Y):
    n = X.shape[0]
    m = Y.shape[0]
    D = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
            D[i,j] = np.sqrt(np.sum((X[i,:]-Y[j,:])**2))
    return D

def euclidean_vectorized(X,Y):
    x2=np.sum(X**2,axis=1).reshape(-1,1)
    y2=np.sum(Y**2,axis=1).reshape(1,-1)
    xy=X@Y.T
    D=np.sqrt(x2+y2-2*xy)
    return D

rng=np.random.default_rng(42)
X=rng.normal(0,1,size=(200,50))
Y=rng.normal(0,1,size=(100,50))

t0=time.time()
D_loop=euclidean_loop(X,Y)
t1=time.time()
print("Loop time:",t1-t0)

t0=time.time()
D_vectorized=euclidean_vectorized(X,Y)
t1=time.time()
print("Vectorized time:",t1-t0)

Loop time: 0.08896970748901367
Vectorized time: 0.0011065006256103516


## 9.组合收益、协方差、风险

In [53]:
rng=np.random.default_rng(42)
T, N = 252, 10

ret = rng.normal(0.005, 0.02, size=(T, N))
w=np.ones(N)/N

port_ret = ret @ w
ann_ret = port_ret.mean() * 252         #年化收益率
ann_vol = port_ret.std() * np.sqrt(252) #年化波动率
sharpe_ratio = ann_ret / ann_vol        #夏普比率
print("Annualized Return:", ann_ret)
print("Annualized Volatility:", ann_vol)    
print("Sharpe Ratio:", sharpe_ratio)

cov = np.cov(ret, rowvar=False)
print("Covariance Matrix:\n", cov)

port_vol = np.sqrt(w @ cov @ w)         #组合波动率
print("Portfolio Volatility:", port_vol)

mrc = cov @ w / port_vol                 #边际风险贡献
print("Marginal Risk Contribution:", mrc)
trc = mrc * w                            #总风险贡献
print("Total Risk Contribution:", trc)
print("Sum of Total Risk Contributions:", trc.sum()) #总风险贡献之和等于组合波动率
rc = trc / port_vol                      #风险贡献占比
print("Risk Contribution:", rc)
print("Sum of Risk Contributions:", rc.sum()) #风险贡献占比之和等于 1

Annualized Return: 1.056089380180631
Annualized Volatility: 0.10313632461606732
Sharpe Ratio: 10.23974224514983
Covariance Matrix:
 [[ 3.87086240e-04  1.85470554e-05 -4.05414589e-06  2.76623862e-05
   7.47109192e-06 -9.80544289e-06 -1.27566575e-05 -3.59603079e-05
   9.29089959e-06 -1.30422999e-05]
 [ 1.85470554e-05  3.64783668e-04  9.99662521e-07 -1.25651136e-05
   6.87643121e-06 -3.38828627e-06  4.11890597e-06 -1.71898168e-05
   2.60346477e-05 -3.24394800e-05]
 [-4.05414589e-06  9.99662521e-07  3.81482418e-04  2.42652848e-05
   6.88403039e-06  1.89819740e-05  1.75612276e-05 -1.56379257e-05
  -3.55369398e-05 -1.28789961e-06]
 [ 2.76623862e-05 -1.25651136e-05  2.42652848e-05  4.25096839e-04
   3.55898117e-05  3.81587482e-05 -3.61123691e-05 -4.22177389e-05
   1.84032601e-05  1.51155643e-05]
 [ 7.47109192e-06  6.87643121e-06  6.88403039e-06  3.55898117e-05
   3.52357287e-04  5.56587258e-05  2.49594264e-05 -4.12105751e-05
   2.27489375e-05  1.36279860e-05]
 [-9.80544289e-06 -3.38828627e-06

## 10.量化中的常见numpy操作

In [ ]:
ret = rng.normal(size=(3, 3))
print("Returns:\n", ret)

cum_ret = np.cumprod(1 + ret, axis=0) - 1 # 计算累积收益率
print("Cumulative Returns:\n", cum_ret)

cum_sum = np.cumsum(ret, axis=0)
print("Cumulative Sum:\n", cum_sum)

diff = np.diff(ret, axis=0)
print("Differences:\n", diff)

sorted_ret = np.sort(ret, axis=0)
print("Sorted Returns:\n", sorted_ret)

rank_ret = np.argsort(ret, axis=0)  #argsort返回的是排序后的索引值
print("Ranks:\n", rank_ret)

index_max = np.argmax(ret, axis=0)   #argmax返回的是最大值的索引值
index_min = np.argmin(ret, axis=0)
print("Index of Max Returns:\n", index_max)
print("Index of Min Returns:\n", index_min)

count_positive = np.sum(ret > 0, axis=0)    #统计每个列中正收益的数量
print("Count of Positive Returns:\n", count_positive)

clipped = np.clip(ret, -1, 1)  #将收益率限制在[-0.01, 0.01]之间
print("Clipped Returns:\n", clipped)

Returns:
 [[-0.21524446  1.78229379 -0.21379686]
 [-1.80047869  1.89304889  0.68239251]
 [-0.07001286 -0.37141774  1.08235193]]
Cumulative Returns:
 [[-0.21524446  1.78229379 -0.21379686]
 [-1.62818009  7.04931196  0.32270227]
 [-1.58419941  4.05965473  1.75433163]]
Cumulative Sum:
 [[-0.21524446  1.78229379 -0.21379686]
 [-2.01572315  3.67534268  0.46859565]
 [-2.08573601  3.30392494  1.55094758]]
Differences:
 [[-1.58523424  0.11075509  0.89618937]
 [ 1.73046583 -2.26446662  0.39995942]]
Sorted Returns:
 [[-1.80047869 -0.37141774 -0.21379686]
 [-0.21524446  1.78229379  0.68239251]
 [-0.07001286  1.89304889  1.08235193]]
Ranks:
 [[1 2 0]
 [0 0 1]
 [2 1 2]]
Index of Max Returns:
 [2 1 2]
Index of Min Returns:
 [1 2 0]
Count of Positive Returns:
 [0 2 2]
Clipped Returns:
 [[-0.21524446  1.         -0.21379686]
 [-1.          1.          0.68239251]
 [-0.07001286 -0.37141774  1.        ]]


In [55]:
x=np.array([1.0, np.nan, 3.0])
print(np.isnan(x))  # 检查 NaN
print(np.nanmean(x))  # 计算均值，忽略 NaN  
print(np.nanstd(x))  # 计算标准差，忽略 NaN 

a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
print(np.vstack((a,b)))  # 垂直堆叠
print(np.hstack((a,a)))  # 水平堆叠

[False  True False]
2.0
1.0
[[1 2]
 [3 4]
 [5 6]]
[[1 2 1 2]
 [3 4 3 4]]


In [56]:
# z-score 标准化
z_scores = (ret - np.mean(ret, axis=0, keepdims=True)) / np.std(ret, axis=0, keepdims=True)
print("Z-scores:\n", z_scores)
print("Mean of Z-scores (should be close to 0):\n", z_scores.mean(axis=0))
print("Std of Z-scores (should be close to 1):\n", z_scores.std(axis=0))

Z-scores:
 [[ 0.6124305   0.65331389 -1.34849309]
 [-1.4101612   0.7595685   0.30522785]
 [ 0.7977307  -1.41288239  1.04326524]]
Mean of Z-scores (should be close to 0):
 [-1.48029737e-16  2.22044605e-16  0.00000000e+00]
Std of Z-scores (should be close to 1):
 [1. 1. 1.]
